version: '3'
services:
  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8080:8080"
    links:
      - guacd
      - mysql
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacdb
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacpass
      GUACD_HOSTNAME: guacd

  guacd:
    image: guacamole/guacd
    restart: always

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: guacdb
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacpass
    volumes:
      - ./mysql:/var/lib/mysql